---
name: Diff Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
    - uses: tj-actions/changed-files@v42
      id: changed-files
      with:
        files: '**/*.md'
    - env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        git remote add etcd ${{ github.event.pull_request.base.repo.clone_url }}
        git fetch etcd
        npm install -g markdownlint-cli
        has_failures=false
        for file in ${CHANGED_FILES}; do
          diff=$(git diff origin/${{ github.event.pull_request.base.ref }} --color=always -- "$file")
          disabled_rules=""
          if ! grep "@@ -1," <(echo "$diff") &>/dev/null; then
            disabled_rules="MD041"
          fi
          echo "::group::$file linter results"
          if ! echo "$diff" | awk '{ if (match($0, /^(\033\[32m\+\033\[m\033\[32m|[^\033])(.*)\033\[m$/, m)) { print m[2] } if (match($0, /^\033\[32m\+\033\[m$/)) { print "" } }' | markdownlint -s --disable "$disabled_rules"; then
            has_failures=true
            echo "::error::$file has linter issues"
          fi
          echo "::endgroup::"
        done
        if [ "$has_failures" ]; then
          exit 1
        fi
