---
name: Lint Markdown file changes
on: [pull_request]
permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
    - uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c # v44.5.7
      id: changed-files
      with:
        files: '**/*.md'
    - run: npm install -g markdownlint-cli2
    - env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        BASE_REF: ${{ github.event.pull_request.base.ref }}
        BASE_CLONE_URL: ${{ github.event.pull_request.base.repo.clone_url }}
        HEAD_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}
      run: make markdown-diff-lint
