---
name: Update Website on Release Nightly
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    - cron: '35 02 * * *' # runs every day at 09:25 UTC
  workflow_dispatch:

jobs:
  v3_4:
    uses: ./.github/workflows/update-release-version-template.yaml
    with:
      release: v34
  v3_5:
    uses: ./.github/workflows/update-release-version-template.yaml
    with:
      release: v3.5
